// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1jiOoT4AUcO794SYk3Faeyuj0MnWV8yk',
    appId: '1:944098835470:web:350b33cc5474df84d7105f',
    messagingSenderId: '944098835470',
    projectId: 'messenger-6b5da',
    authDomain: 'messenger-6b5da.firebaseapp.com',
    storageBucket: 'messenger-6b5da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8tAhIIWhqVlDfubL8uOfiTJMxArDzAvY',
    appId: '1:944098835470:android:32d3225ed286e484d7105f',
    messagingSenderId: '944098835470',
    projectId: 'messenger-6b5da',
    storageBucket: 'messenger-6b5da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6eDyXZ-latsk89e7ywoPDI1QNKZQgu5M',
    appId: '1:944098835470:ios:bd91b41088a7236fd7105f',
    messagingSenderId: '944098835470',
    projectId: 'messenger-6b5da',
    storageBucket: 'messenger-6b5da.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6eDyXZ-latsk89e7ywoPDI1QNKZQgu5M',
    appId: '1:944098835470:ios:bd91b41088a7236fd7105f',
    messagingSenderId: '944098835470',
    projectId: 'messenger-6b5da',
    storageBucket: 'messenger-6b5da.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1jiOoT4AUcO794SYk3Faeyuj0MnWV8yk',
    appId: '1:944098835470:web:0bcf63899e674aa7d7105f',
    messagingSenderId: '944098835470',
    projectId: 'messenger-6b5da',
    authDomain: 'messenger-6b5da.firebaseapp.com',
    storageBucket: 'messenger-6b5da.firebasestorage.app',
  );
}
